import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { getPhotos, getSettings } from "@/sanity/lib/fetch";
import { urlFor } from "@/sanity/lib/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const settings = await getSettings();
console.log(settings[0].site_title);

export const metadata: Metadata = {
  title: settings[0].site_title || "Site de Aziyade",
  description: settings[0].site_description || "Generated by create next app",
  openGraph: {
    title: settings[0].site_title || "Site de Aziyade",
    description: settings[0].site_description || "Generated by create next app",
    siteName: settings[0].site_title || "Site de Aziyade",
    images: [
      {
        url: urlFor(settings[0]?.site_image).url(),
        alt:"Logo du site de Aziyade"
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
