import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { getSettings } from "@/sanity/lib/fetch";
import { urlFor } from "@/sanity/lib/image";
import Header from "./components/Header";
// import Footer from "./components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Fonction asynchrone pour générer les métadonnées
export async function generateMetadata(): Promise<Metadata> {
  const settings = await getSettings();

  return {
    title: settings[0]?.site_title || "Site de Aziyade",
    description:
      settings[0]?.site_description || "Generated by create next app",
    openGraph: {
      title: settings[0]?.site_title || "Site de Aziyade",
      description:
        settings[0]?.site_description || "Generated by create next app",
      siteName: settings[0]?.site_title || "Site de Aziyade",
      images: [
        {
          url: urlFor(settings[0]?.site_image).url(),
          alt: "Logo du site de Aziyade",
        },
      ],
    },
  };
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main className="
        ">{children}</main>
      </body>
    </html>
  );
}
